# Generated by Django 2.1 on 2018-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('zipCode', models.CharField(max_length=50)),
                ('sellPrice', models.IntegerField()),
                ('date', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'sold',
                'db_table': 'sold_solddata',
            },
        ),
    ]
