# Generated by Django 2.1 on 2018-09-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sold', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solddata',
            options={'managed': False, 'verbose_name_plural': 'sold'},
        ),
    ]
