# Generated by Django 2.1 on 2018-09-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sold', '0002_auto_20180929_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solddata',
            options={'managed': True, 'verbose_name_plural': 'sold'},
        ),
    ]
