# Generated by Django 2.1 on 2018-09-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sold', '0004_auto_20180929_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solddata',
            options={'managed': False, 'verbose_name_plural': 'sold'},
        ),
    ]
